[package]
name = "kalopsia-os"
version = "0.1.0"
edition = "2024"

# Binary doesn't support builds in test and bench modes
[[bin]]
name = "kalopsia-os"
test = false
bench = false

[dependencies]
bootloader = "0.9"
